import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/Navbar";
// import "./globals.css";
import Footer from "@/components/Footer";
import ContextMain from "@/contexts/context";
import Navtoggle from "@/components/Navtoggle";
import Footertoggle from "@/components/Footertoggle";
import Provider from "@/components/Provider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} text-black overflow-x-hidden`}>
        <Provider>
          <ContextMain>
            <Navbar />
            <NextTopLoader showSpinner={false} color="#E63956" />
            {children}
            <Footer />
          </ContextMain>
        </Provider>
      </body>
    </html>
  );
}
