import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/Navbar";
// import "../../app/global.css";
import Footer from "@/components/Footer";
import MaxWrapper from "@/components/ui/MaxWrapper";
import ContextMain from "@/contexts/context";
import Provider from "@/components/Provider";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} text-black overflow-x-hidden`}>
        <Provider>
          <ContextMain>
            {/* <Navtoggle /> */}
            {children}
            {/* <Footertoggle /> */}
          </ContextMain>
        </Provider>
      </body>
    </html>
  );
}
