import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Navbar from "@/components/ui/Navbar";
import "./globals.scss";
import Footer from "@/components/Footer";
import ContextMain from "@/contexts/context";
import Navtoggle from "@/components/Navtoggle";
import Footertoggle from "@/components/Footertoggle";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} overflow-x-hidden`}>
        <NextTopLoader />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
